### ISSUE TITLE
Uganda <- no more clusters

### ISSUE THREAD

**Issue by achafetz** [jason-p-pickering/data-pack-importer#10]
Don't know if this affects either of you, but Uganda decided to drop their clusters. 

[Here is the updated cluster list.](https://github.com/achafetz/DataPack/blob/master/RawData/COP18Clusters.csv)

**Comment by jason-p-pickering** [comment]
It may. Will keep this open.

**Comment by jason-p-pickering** [comment]
Assume this has been fixed @achafetz
