### ISSUE TITLE
Adding in Validation Columns?

### ISSUE THREAD

**Issue by achafetz** [jason-p-pickering/data-pack-importer#11]
One feature currently missing from the disagg tool is a validation check to ensure the disagg allcations sum to 100% for each grouping. Would it be possible for me to add in 1 column per disagg grouping in each tab prior to the data pack target columns?

For example, TX_CURR would have a validation check for <15 and 15+ (the gold headed columns in the image below).

![image](https://user-images.githubusercontent.com/8933069/35930947-5100dde8-0c01-11e8-9169-b5b1aefd2f38.png)

**Comment by jason-p-pickering** [comment]
@achafetz how about the HTS disagg tool? Will there be changes there as well?

**Comment by achafetz** [comment]
yep! and sorry, I didn't get a chance to update the VBA to run a beta version yesterday.  

Here is the template though. It will look exactly like this, minus the first 3 tabs - https://github.com/achafetz/DataPack/tree/master/TemplateGeneration

**Comment by jason-p-pickering** [comment]
Seems to be fine in ed063f77baf8d5322c54600868c24a682e999ece. Closing
