### ISSUE TITLE
BWA --> 3 new clusters

### ISSUE THREAD

**Issue by achafetz** [jason-p-pickering/data-pack-importer#12]
J.Roffenbender [added 3 clusters](https://github.com/achafetz/DataPack/blob/master/RawData/COP18Clusters.csv) for Botswana. New Data Pack was run yesterday to include them. Plan on rerunning the Disagg Tools for them today.

Additions in the table below with newly assigned PSNU cluster UIDs:

operatingunit | psnu | psnuuid | currentsnuprioritization | cluster_psnu | cluster_snu1 | cluster_psnuuid | cluster_currentsnuprioritization
-- | -- | -- | -- | -- | -- | -- | --
Botswana | Serowe | YmeyoDakwFX | 4 - Sustained | SerowePalapye Cluster | [Clustered] | eIMbzhLw0CH | [NOT DEFINED]
Botswana | Palapye | TcLMNlsgbcz | [NOT DEFINED] | SerowePalapye Cluster | [Clustered] | eIMbzhLw0CH | [NOT DEFINED]
Botswana | Charleshill | v3v0gu2Gtol | [NOT DEFINED] | CharleshillGhanzi Cluster | [Clustered] | xy7foRJ2vp9 | [NOT DEFINED]
Botswana | Ghanzi | saOJtBcENzM | 6 - Sustained: Commodities | CharleshillGhanzi Cluster | [Clustered] | xy7foRJ2vp9 | [NOT DEFINED]
Botswana | Moshupa | xLLFT8x1CF5 | [NOT DEFINED] | MoshupaSouthern Cluster | [Clustered] | LRwB4ApIz9u | [NOT DEFINED]
Botswana | Southern | LEUjALXInGD | 1 - Scale-Up: Saturation | MoshupaSouthern Cluster | [Clustered] | LRwB4ApIz9u | [NOT DEFINED]

**Comment by jason-p-pickering** [comment]
We are in the process of merging these two repos. Please provide a definitive URL for where the data can be accessed @achafetz

**Comment by achafetz** [comment]
DataPack/RawData/COP18Clusters.csv

https://github.com/achafetz/DataPack/blob/master/RawData/COP18Clusters.csv

**Comment by jason-p-pickering** [comment]
Assume this has been fixed @achafetz
