### ISSUE TITLE
Change site and mech list name column to 500 pix

### ISSUE THREAD

**Issue by jason-p-pickering** [jason-p-pickering/data-pack-importer#26]
This may only be an  OpenOffice issue. @achafetz @jacksonsj can  you check in  Excel and see if these column widths are correct? Otherwise, we may need to set them. 

![image](https://user-images.githubusercontent.com/2968061/36638843-7f86469e-1a07-11e8-915f-f623ee735b84.png)

**Comment by achafetz** [comment]
OpenOffice is adding a drop down where it doesn't exist in MS Excel we're good on that front. 

To your point about column formatting, we need to define the length in this tab for column A. Currently 72 pixels, and would recommend ~500.

![image](https://user-images.githubusercontent.com/8933069/36640657-00f56b78-1a2c-11e8-96f4-ce94bc5701d6.png)

**Comment by jason-p-pickering** [comment]
OBE.
