### ISSUE TITLE
Subtotals do not appear to be working

### ISSUE THREAD

**Issue by jason-p-pickering** [jason-p-pickering/data-pack-importer#27]
Formula has the syntax of 

```
=SUBTOTAL(109,INDIRECT($B$1&"["&E6&"]"))
```

This seems to work for me

```
=SUM($E$7:$E$1048576)
```

@achafetz any thoughts here?

**Comment by achafetz** [comment]
As discussed, `=SUBTOTAL(109,...)` shows the sum of filtered values so this is preferable over `SUM()`. Seemed to be working on the latest output :)
