### ISSUE TITLE
Remap DataPack IDs to DATIM data elements and catptioncombo UIDs

### ISSUE THREAD

**Issue by jason-p-pickering** [jason-p-pickering/data-pack-importer#3]
@jacksonsj I need the mapping file which will be used to map data data pack data element IDs to DATIM UIDs. Can you provide that ASAP?

**Comment by jacksonsj** [comment]
Completed and sent

**Comment by jason-p-pickering** [comment]
Closed via d4ac99aa5cc55403c332b810ea347064f50e9dcf
