### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by achafetz** [jason-p-pickering/data-pack-importer#30]
Asking for a friend

>To whom it may concern;
>
>Please fix number formatting -> "#,##0;-#,##0;;"
> 
>Love,
> A concerned citizen

![image](https://user-images.githubusercontent.com/8933069/36645578-b4147b44-1a73-11e8-807e-da76ecea7b68.png)

**Comment by jason-p-pickering** [comment]
Fixed in f7e72c6f3cf5e4963949e23880454a35ea3677f5
