### ISSUE TITLE
Burundi data pack hierarchy change and re-run

### ISSUE THREAD

**Issue by pvinayak001** [jason-p-pickering/data-pack-importer#35]
https://github.com/ICPI/COP18/issues/92

Jasmine:
Request received from SI Advisor (Yesenia)
Approved by ICPI
Assigned to Aaron and Pooja

Request
Based on this morning's discussion, Burundi will need to make a change to our DATIM hierarchy. We need to combine/cluster Bujumbura Mairie and Bujumbura Rural into Bujumbura. Also, we are proposing (with Chair support) to reactivate Gitega, which already exists in DATIM and the Datapack--just noting as an FYI in case of consequence.

Apart from the aforementioned, no other changes.

Please let me know what is required, timelines and next steps for the update.

I will also swing by the ICPI helpdesk again for follow up.

Aaron:
sent cluster form to Y.Saulino to complete and then I can regenerate the Data Pack (will be done off FV Q4v3_2, current is v2_1).Data Pack should be a quick run (<20min) once the file is received; the DTs will take longer since I have to access the server and move files over (on this internet with poor bandwidth)
--

@jason-p-pickering @jacksonsj @davidhuser FYI

**Comment by pvinayak001** [comment]
Please let me know what additional info you need and I will follow up.

**Comment by jason-p-pickering** [comment]
Not an issue for this repo but rather the COP18 repo which generates the distributions. 

FYI @jacksonsj @pvinayak001
