### ISSUE TITLE
Identified variation in Disagg Tool structure

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#47]
For Zimbabwe and DRC, fields in "Already Alloc Targets" are as follows:

kp_prev_f_pwid_fy19 | D_kp_prev_fsw_fy19 | kp_prev_m_pwid_fy19 | D_kp_prev_msm_not_sw_fy19 | kp_prev_msm_sw_fy19 | kp_prev_prison | kp_prev_tg_notsw | kp_prev_tg_sw | kp_mat_f | kp_mat_m | D_ovc_hivstat_fy19 | D_pmtct_art_already_fy19 | D_pmtct_art_new_fy19 | D_pmtct_eid_u2mo_fy19 | D_pmtct_eid_o2mo_fy19
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

For other countries and in data-pack-importer schema (as provided in "final" template from @achafetz), fields in same tab are as follows:

kp_prev_f_pwid | kp_prev_fsw | kp_prev_m_pwid | kp_prev_msm_notsw | kp_prev_msm_sw | kp_prev_prison | kp_prev_tg_notsw | kp_prev_tg_sw | kp_mat_f | kp_mat_m | ovc_hivstat | D_pmtct_art_already_fy19 | D_pmtct_art_new_fy19 | D_pmtct_eid_u2mo_fy19 | D_pmtct_eid_o2mo_fy19
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

This causes a validation error for files using the first version as it is out-of-sync with version 2 as captured in data-pack-importer schemas.

**Comment by jacksonsj** [comment]
Potential fix: Copy correct field names from version 2 above into row 6 of Already Alloc Targets for Disagg Tools using version 1

**Comment by jason-p-pickering** [comment]
I think this was documented in the change log for the DataPack? 

@achafetz can maybe explain what is going on with this?

**Comment by jacksonsj** [comment]
@achafetz - I also noticed in one tool, but not in others, that the country team had created a new tab called KP_MAT. I think this corresponds to guidance I see on the [Change Log](https://github.com/achafetz/DataPack/wiki/COP18-Disagg-Tool-Change-Log), bullet five. How should we handle this change from the original template?

**Comment by jason-p-pickering** [comment]
Not fixing here. 

Added a small feature to echo which tables and fields are wrong.
