### ISSUE TITLE
Potentially incorrect assignment of PLHIV dataelement

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#49]
https://github.com/jason-p-pickering/data-pack-importer/blob/0e70f5c87d0c078f72913daad12ea6fdcf5aae36/R/data-pack-importer.R#L241

This line assigns PLHIV values received from Data Pack to "Rom79qVjNVb" instead of "rORzrY9rpQ1" as seen below in data entry screens:

![image](https://user-images.githubusercontent.com/31488407/36884862-87f19326-1db1-11e8-9a45-f8040633ebc9.png)

**Comment by jason-p-pickering** [comment]
Addressed at least in 51501d529ecf95ca2b438457b2d367cc734b9dcc
