### ISSUE TITLE
Change in tabs needed to be imported from Data Pack

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#5]
Just uploaded a [new version of map](https://github.com/jason-p-pickering/data-pack-importer/blob/master/data-raw/DataPackCodes.csv) between Data Pack Codes and DATIM DE.CoC UIDs. This version specifies which document (DisaggTool or HTS DisaggTool) and in which tabs each data pack code is found.

Uniquely selecting DataPackFilename and DataPackTabName will give a list of which tabs to keep within each tool.

Note the following tabs that are outliers in the DisaggTool:

## Already Alloc Targets

- KP_MAT
- KP_PREV
- OVC_HIVSTAT
- PMTCT_ART (denominator)
- PMTCT_EID (denominator)

## IMPATT Table
- plhiv_fy19

**Comment by jacksonsj** [comment]
@achafetz - Please notify via this issue thread if any of the following changes occur to either DisaggTool:

- Changes to code names
- Changes to tab names
- Need to import data in additional tab
- Deletions of codes from any tab
- Reordering of codes in any tab

**Comment by jason-p-pickering** [comment]
@jacksonsj closing this issue for now, as I think it has been addressed in d4ac99aa5cc55403c332b810ea347064f50e9dcf. 

@achafetz if additional structural changes happen, please raise a new issue.
