### ISSUE TITLE
Military Prioritizations being read as NAs --> throwing off negative values check

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#64]
I received this error when validating Uganda's non-HTS Disagg Tool:

![image](https://user-images.githubusercontent.com/31488407/37018561-d305b692-20e2-11e8-816d-5714da565709.png)

After investigation, I found this:

![image](https://user-images.githubusercontent.com/31488407/37018574-df2f20ac-20e2-11e8-9d97-34ee45ccb7ea.png)

"Mil" is not defined as an option in "./data-raw/impatt_options_set.json" so is being left in the value column as a string.

When the below code is run:

```
has_negative_numbers <- as.numeric(df$value) < 0
if (any(has_negative_numbers)) {
    foo <- df[has_negative_numbers, ]
    warning("Negative values were found in the data!")
    print(foo)
  }
```

"Mil" prioritization becomes NA, causing the _any_ function to yield NA, explaining the error above

**Comment by jason-p-pickering** [comment]
OK, as far as I can tell, "Mil" is not a correct prioritization. 

https://www.datim.org/api/optionSets/M3SmpE7BgSS?fields=options[id,name]

**Comment by jason-p-pickering** [comment]
![image](https://user-images.githubusercontent.com/2968061/37019630-50ecc358-2119-11e8-82c0-7cd0f68e6a5b.png)

**Comment by jacksonsj** [comment]
It's not a valid option in DATIM, right. But Disagg Tool includes it as an option:

![image](https://user-images.githubusercontent.com/31488407/37019766-8e0bc932-20e7-11e8-9fc0-3fcdbce19293.png)

Suggest a change something like this, in ImportSheet function:

![image](https://user-images.githubusercontent.com/31488407/37019989-4b29c460-20e8-11e8-8b7a-6697d874670d.png)

**Comment by jason-p-pickering** [comment]
Implemented.
