### ISSUE TITLE
Handling of very small values from the Disagg Tool

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#69]
I ran into an issue with UG's file related to this. Small positive values produced site-level values between 0 and 0.5. These were rounded to 0 and dropped in transition between Disagg Tool and Site Level Tool. The result was immediate differences between Disagg Tool values and Site Level roll-ups. Current process makes it difficult for users to identify where this has happened.

**Possible Solutions:**
1) Keep as is. Make this clear in guidance.
2) Push rounding operations to right before exporting to site level tool (move from distributeSite function to export_site_level_tool or write_site_level_sheet). Then, do not drop values between 0 and 0.5 where these were produced by our automatic distribution process (ok to drop these small positive values where inherited directly from Disagg Tool). Write these to site level tool as 0s to indicate where this has occurred.

So far, option 1 has been fine. Felt the need to flag and ask feedback.

**Comment by jason-p-pickering** [comment]
@jacksonsj possible solution in https://github.com/jason-p-pickering/data-pack-importer/pull/70

**Comment by jason-p-pickering** [comment]
Should be handled correctly in fefd4e6c64cf910155ad1b7b01abc384ef22c0e0
