### ISSUE TITLE
Import of Follow on mechs

### ISSUE THREAD

**Issue by jason-p-pickering** [jason-p-pickering/data-pack-importer#7]
@jacksonsj Not sure how to handle the follow on mechs. I would guess you need that information from the parser. My initial thought was to produce a data structure like

```
{ data : [...],
  follow_on_mechs: [...] }
```
which would contain both objects. The `data` object would be just a normal data frame as we have discussed, and the follow-on mechs would contain some map which would be parsed from that sheet. Is there any need to worry about this?

**Comment by jacksonsj** [comment]
@jason-p-pickering We won't need the map to go into DATIM anywhere, but I'll need it for one part of my distribution function. So if you can validate its structure per above and then pull it in as a DF or something I can easily reference in my script, that'd be great.

**Comment by jason-p-pickering** [comment]
Implemented in at least ed063f77baf8d5322c54600868c24a682e999ece. Closing.
