### ISSUE TITLE
prepare_export_to_datim dropping dataElements

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#76]
@jason-p-pickering - for some reason the `prepare_export_to_datim` function is dropping select dataElements when I attempt to produce PSNU import files. 

Example: Namibia, `PMTCT_STAT (D, DSD, Age/Sex)` (`l7M8cLykXri`) getting dropped in import file.

Screenshot of these values in Disagg Tool:

![image](https://user-images.githubusercontent.com/31488407/37181322-75d28f30-22fa-11e8-9d57-65eb1e853e3d.png)

When I run:
`DataPackR(disagg_tool, distribution_method = distribution_year, support_files_path = support_files)`

I don't see these in the resulting CSV file (`l7M8cLykXri` should appear between `KobylmT2gvc` and `M5m4zQMsdX5`):

![image](https://user-images.githubusercontent.com/31488407/37182367-e8efcfec-22fe-11e8-80f4-85e8384340e8.png)

However, when I break `prepare_export_to_datim` apart and run code this way:

```
d<- ImportSheets(wb_path,distribution_method = distribution_method,support_files_path = support_files_path)

if (d$wb_info$wb_type %in% c("HTS", "NORMAL")) {
    file_prefix <- "/psnu_import_"
    d <- distributeCluster(d)
  } else if (d$wb_info$wb_type %in% c("HTS_SITE", "NORMAL_SITE")) {
    file_prefix <- "/site_import_"
  }

  export_data <- d$data %>%
    dplyr::mutate(value = as.character(round_trunc(as.numeric(value)))) %>%
    dplyr::filter(!(value < 1)) %>%
    dplyr::select(
      dataelement,
      period,
      orgunit,
      categoryoptioncombo,
      attributeoptioncombo,
      value
    ) %>%
    na.omit()

  output_file_path <- paste0(
    dirname(d$wb_info$wb_path),
    file_prefix,
    d$wb_info$wb_type,
    "_",
    d$wb_info$ou_name,
    "_",
    format(Sys.time(), "%Y%m%d%H%M%S"),
    ".csv"
  )

  utils::write.table(
    export_data,
    file = output_file_path,
    quote = TRUE,
    sep = ",",
    row.names = FALSE,
    col.names = TRUE
  )
```

I see those values in the export (appearing between `KobylmT2gvc` and `M5m4zQMsdX5`):

![image](https://user-images.githubusercontent.com/31488407/37182339-c810dd52-22fe-11e8-9e7d-e76275cedbac.png)

Can't figure out a cause.

This seems to be happening for many dataElements for many OUs and is raising numerous flags in datim validations.

**Comment by jacksonsj** [comment]
This seems to be related to my function... distributeCluster. Still looking into why.

**Comment by jacksonsj** [comment]
Problem is here:
https://github.com/jason-p-pickering/data-pack-importer/blob/f4e9db13fffd5bbc75a8334513663028155e2d9f/R/distribution.R#L104

![image](https://user-images.githubusercontent.com/31488407/37183343-9405435e-2303-11e8-9eb6-1ed74007a091.png)


Should only alter values if the orgunit is a Cluster. If a PSNU within a clustering country, value should remain as it is received.

Will adjust and commit change.

**Comment by jason-p-pickering** [comment]
Believe this has been solved with alterations to `distributeCluster` function.
