### ISSUE TITLE
Changes/Change Requests to (Normal) Disagg Tool

### ISSUE THREAD

**Issue by achafetz** [jason-p-pickering/data-pack-importer#9]
I went through the Disagg Tool this afternoon to align it with the Target entry screens. I've detailed some proposed changes (or a couple I already changed due to minor issues or were necessary to protect the tool's integrity). I'd like your okay on making these structural changes.
[COP18DisaggToolTemplate v2018.01.29.zip](https://github.com/jason-p-pickering/data-pack-importer/files/1675110/COP18DisaggToolTemplate.v2018.01.29.zip)

- HTS_SELF
  - **potential issue - target entry screens show - fine compared with the new "finerer" which are reflected in the MER 2.0 guidance and Disagg Tool**
- PMTCT
  - **fixed #REF formula error in the Age/Sex disaggs**
  - can I rename this sheet PMTCT_STAT rather than just PMTCT?
  - can I remove a middle column for Sex disagg no longer in entry screen, can it be deleted?
- TB_ART
  - **can I remove 2 allocation columns for ART HIVStatus, as they are no longer being used/collected?**
  - can I remove last column for HIVStatus, no longer collected?
-TB_PREV
  - removed group header (row 3) in four columns (allocation and target for D and N); grouping all of TherapyType together for Denom and Num
  - can I remove two middle columns for HIVStatus, no longer collected?
- TX_CURR
  - can I remove last column for HIVStatus, no longer collected?
- TX_NEW
  - can I remove a middle columns for HIVStatus, no longer collected?
- TX_PLVS
  - added DENOMINATOR to all header labels in row 2
  - **issue with allocation variable names row 6, replaced with correct ones**
  - can I remove a middle column for HIVStatus, no longer collected?  
- TX_RET
  - can I remove two middle columns for HIVStatus, no longer collected?
- TX_TB
  - added DENOMINATOR to all header labels in row 2
  - can I remove two middle columns for HIVStatus, no longer collected?
- VMMC
  - can I remove two middle column for Sex, no longer collected?

**Comment by jason-p-pickering** [comment]
Basically, you can do all of this. Codes which are not in (here)[https://github.com/jason-p-pickering/data-pack-importer/blob/master/data-raw/DataPackCodes.csv] will be dropped by (this)[ https://github.com/jason-p-pickering/data-pack-importer/blob/master/R/data-pack-importer.R#L122]
. 

This will require an update to the schemas, and thus, and update to the data pack template which you will need to submit to me.

**Comment by achafetz** [comment]
Thanks. Will do.

**Comment by achafetz** [comment]
updated template and variable output. let me know if you both need anything else as a result of this change.

[Updated_DT_and_VariableList.zip](https://github.com/jason-p-pickering/data-pack-importer/files/1675193/Updated_DT_and_VariableList.zip)

**Comment by jason-p-pickering** [comment]
Think this has been taken care of so closing.
